-- MySQL Script generated by MySQL Workbench
-- qui 25 abr 2019 14:40:05 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tcc` DEFAULT CHARACTER SET utf8 ;
USE `tcc` ;

-- -----------------------------------------------------
-- Table `tcc`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `horario` TIME NOT NULL,
  `domingo` TINYINT(1) NOT NULL,
  `segunda` TINYINT(1) NOT NULL,
  `terca` TINYINT(1) NOT NULL,
  `quarta` TINYINT(1) NOT NULL,
  `quinta` TINYINT(1) NOT NULL,
  `sexta` TINYINT(1) NOT NULL,
  `sabado` TINYINT(1) NOT NULL,
  `somTocar` TINYINT(1) NOT NULL,
  `somTempoDuracao` INT(2) NOT NULL,
  `somVolume` INT(3) NOT NULL,
  PRIMARY KEY (`idEvento`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
